apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: zookeeper
  labels:
    service: zookeeper
spec:
  ports:
    - name: peer
      port: 2888
    - name: leader-election
      port: 3888
  clusterIP: None
  selector:
    app: zookeeper
