---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
    service: zookeeper
spec:
  ports:
    - name: client
      port: 2181
  selector:
    service: zookeeper
